Update quickstart.md
added missing step where will leads the user to error page after the theme activation.

```
Fatal error: Uncaught WPEmergeTheme\Concerns\JsonFileNotFoundException: The required manifest.json file is missing. Please run one of the build commands to generate it. in /wp-content/themes/your-theme-name/vendor/htmlburger/wpemerge-theme-core/src/Assets/Manifest.php:27 Stack trace: #0 /wp-content/themes/your-theme-name/vendor/htmlburger/wpemerge-theme-core/src/Concerns/ReadsJsonTrait.php(52): WPEmergeTheme\Assets\Manifest->load('/Users/ihsanber...') #1 /wp-content/themes/your-theme-name/vendor/htmlburger/wpemerge-theme-core/src/Concerns/ReadsJsonTrait.php(66): WPEmergeTheme\Assets\Manifest->getAll() #2 /wp-content/themes/your-theme-name/vendor/htmlburger/wpemerge-theme-core/src/Assets/Assets.php(96): WPEmergeTheme\Assets\Manifest->get('images/favico in /wp-content/themes/your-theme-name/vendor/htmlburger/wpemerge-theme-core/src/Assets/Manifest.php on line 27
```